final String tableCartProduct3 = 'cartProduct3';
final String columnTitle = 'title';
final String columnImage = 'image';
final String columnPrice = 'price';
final String columnProductID = 'productID';
final String columnQuantity = 'quantity';
final String columndescription = 'description';
// final String columnQuantity = 'quantity';
// final CASHED_USER_DATA = 'CASHED_USER_DATA';
